import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ReduxProvider from "@/store/reduxProvider";
import HeaderLayout from "./(layout)/headerLayout/page";
import FooterLayout from "./(layout)/footerLayout/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider> <HeaderLayout/> {children} <FooterLayout/>
      <Toaster position="top-center"/></ReduxProvider>
       
      </body>
    </html>
  );
}
